#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : librdmacm
Version  : 1.0.21
Release  : 1
URL      : https://www.openfabrics.org/downloads/rdmacm/librdmacm-1.0.21.tar.gz
Source0  : https://www.openfabrics.org/downloads/rdmacm/librdmacm-1.0.21.tar.gz
Summary  : Userspace RDMA Connection Manager
Group    : Development/Tools
License  : BSD-2-Clause GPL-2.0
Requires: librdmacm-bin
Requires: librdmacm-lib
Requires: librdmacm-doc
BuildRequires : libibverbs-dev

%description
librdmacm provides a userspace RDMA Communication Managment API.

%package bin
Summary: bin components for the librdmacm package.
Group: Binaries

%description bin
bin components for the librdmacm package.


%package dev
Summary: dev components for the librdmacm package.
Group: Development
Requires: librdmacm-lib
Requires: librdmacm-bin
Provides: librdmacm-devel

%description dev
dev components for the librdmacm package.


%package doc
Summary: doc components for the librdmacm package.
Group: Documentation

%description doc
doc components for the librdmacm package.


%package lib
Summary: lib components for the librdmacm package.
Group: Libraries

%description lib
lib components for the librdmacm package.


%prep
%setup -q -n librdmacm-1.0.21

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/cmtime
/usr/bin/mckey
/usr/bin/rcopy
/usr/bin/rdma_client
/usr/bin/rdma_server
/usr/bin/rdma_xclient
/usr/bin/rdma_xserver
/usr/bin/riostream
/usr/bin/rping
/usr/bin/rstream
/usr/bin/ucmatose
/usr/bin/udaddy
/usr/bin/udpong

%files dev
%defattr(-,root,root,-)
/usr/include/infiniband/ib.h
/usr/include/rdma/rdma_cma.h
/usr/include/rdma/rdma_cma_abi.h
/usr/include/rdma/rdma_verbs.h
/usr/include/rdma/rsocket.h
/usr/lib64/*.so

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man1/*
%doc /usr/share/man/man3/*
%doc /usr/share/man/man7/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
/usr/lib64/rsocket/librspreload.so
/usr/lib64/rsocket/librspreload.so.1
/usr/lib64/rsocket/librspreload.so.1.0.0
